#!/usr/bin/env bash

# Install Claude Code. Installation location originally copied from
# https://docs.anthropic.com/en/docs/claude-code/getting-started

if [[ $EUID -ne $(id -u ${_CONTAINER_USER}) ]]
then
  echo ">Copying config to the remote user's home directory"

  # Copy files over while setting ownership and permissions
  rsync -rp \
      --chown=${_CONTAINER_USER}:${_CONTAINER_USER} \
      --chmod=D755,F644 \
      "home/." "/home/${_CONTAINER_USER}"

  # Separate rsync: hooks need the execute bit, which the config copy's F644
  # would strip.
  rsync -rp \
      --chown=${_CONTAINER_USER}:${_CONTAINER_USER} \
      --chmod=D755,F755 \
      "bin/." "/home/${_CONTAINER_USER}/bin"

  # Create additional Claude Code configuration dirs owned by the container
  # user, to support multiple accounts
  for i in {1..3}
  do
    install -d -o ${_CONTAINER_USER} -g ${_CONTAINER_USER} -m 0755 \
      "/home/${_CONTAINER_USER}/.claude-${i}"
    install -d -o ${_CONTAINER_USER} -g ${_CONTAINER_USER} -m 0755 \
      "/home/${_CONTAINER_USER}/.claude-${i}/projects"

  # Copy files over while setting ownership and permissions
  rsync -rp \
      --chown=${_CONTAINER_USER}:${_CONTAINER_USER} \
      --chmod=D755,F644 \
      "home/.claude/." "/home/${_CONTAINER_USER}/.claude-${i}"
  done

  exec sudo -iu "${_CONTAINER_USER}" "$(realpath $0)" $CLAUDE_CONFIG_DIR
fi

echo ">Switched to the container user"

echo ">Installing Claude Code"

curl -fsSL https://claude.ai/install.sh | bash

echo ">Done installing Claude code"

echo ">Removing default ~/.claude.json. A new one will be generated by Claude Code in CLAUDE_CONFIG_DIR"
rm -f ~/.claude.json
