name: "Build and publish devcontainer image"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish devcontainer image
        if: ${{ github.run_attempt == 1 }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/hube/devcontainer
          cacheFrom: ghcr.io/hube/devcontainer
          push: always

      - name: Build with no cache and publish devcontainer image
        if: ${{ github.run_attempt > 1 }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/hube/devcontainer
          noCache: true
          push: always
